enabled_categories_user:
  type: list
  list_type: category
  default: ""
  description: "Choose which categories that users need to subscribe for."
enabled_tags_user:
  type: list
  list_type: tag
  default: ""
  description: "Choose which tags that users need to subscribe for. The default is 'gated'."
allowed_groups:
  type: list
  list_type: group
  default: ""
  description: "Choose which groups users need to be a member of to view the content."
custom_button_link:
  type: string
  default: "/s/prod_NbacDHyXJsrLNv"
  description: "Choose a custom relative link for the button."